# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newtraceUI.ui'
#
# Created by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogNewTrace(object):
    def setupUi(self, dialogNewTrace):
        dialogNewTrace.setObjectName("dialogNewTrace")
        dialogNewTrace.resize(563, 432)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogNewTrace)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dialogNewTrace)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textExecutable = QtWidgets.QLineEdit(dialogNewTrace)
        self.textExecutable.setObjectName("textExecutable")
        self.horizontalLayout_2.addWidget(self.textExecutable)
        self.buttonGetExecutableFile = QtWidgets.QToolButton(dialogNewTrace)
        self.buttonGetExecutableFile.setObjectName("buttonGetExecutableFile")
        self.horizontalLayout_2.addWidget(self.buttonGetExecutableFile)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(dialogNewTrace)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.textArguments = QtWidgets.QLineEdit(self.groupBox)
        self.textArguments.setObjectName("textArguments")
        self.verticalLayout_2.addWidget(self.textArguments)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxTakeArgumentsFromFile = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxTakeArgumentsFromFile.setObjectName("checkBoxTakeArgumentsFromFile")
        self.horizontalLayout_3.addWidget(self.checkBoxTakeArgumentsFromFile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textArgumentsFile = QtWidgets.QLineEdit(self.groupBox)
        self.textArgumentsFile.setObjectName("textArgumentsFile")
        self.horizontalLayout_4.addWidget(self.textArgumentsFile)
        self.buttonGetArgumentsFile = QtWidgets.QToolButton(self.groupBox)
        self.buttonGetArgumentsFile.setObjectName("buttonGetArgumentsFile")
        self.horizontalLayout_4.addWidget(self.buttonGetArgumentsFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.label_4 = QtWidgets.QLabel(dialogNewTrace)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textStartDirectory = QtWidgets.QLineEdit(dialogNewTrace)
        self.textStartDirectory.setObjectName("textStartDirectory")
        self.horizontalLayout_5.addWidget(self.textStartDirectory)
        self.buttonGetStartDirectory = QtWidgets.QToolButton(dialogNewTrace)
        self.buttonGetStartDirectory.setObjectName("buttonGetStartDirectory")
        self.horizontalLayout_5.addWidget(self.buttonGetStartDirectory)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonRunTrace = QtWidgets.QPushButton(dialogNewTrace)
        self.buttonRunTrace.setObjectName("buttonRunTrace")
        self.horizontalLayout.addWidget(self.buttonRunTrace)
        self.buttonSaveTraceSettings = QtWidgets.QPushButton(dialogNewTrace)
        self.buttonSaveTraceSettings.setObjectName("buttonSaveTraceSettings")
        self.horizontalLayout.addWidget(self.buttonSaveTraceSettings)
        self.buttonNewTraceCancel = QtWidgets.QPushButton(dialogNewTrace)
        self.buttonNewTraceCancel.setObjectName("buttonNewTraceCancel")
        self.horizontalLayout.addWidget(self.buttonNewTraceCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dialogNewTrace)
        QtCore.QMetaObject.connectSlotsByName(dialogNewTrace)

    def retranslateUi(self, dialogNewTrace):
        _translate = QtCore.QCoreApplication.translate
        dialogNewTrace.setWindowTitle(_translate("dialogNewTrace", "New Trace"))
        self.label.setText(_translate("dialogNewTrace", "Executable"))
        self.buttonGetExecutableFile.setText(_translate("dialogNewTrace", "..."))
        self.groupBox.setTitle(_translate("dialogNewTrace", "Command line arguments"))
        self.label_2.setText(_translate("dialogNewTrace", "Text"))
        self.checkBoxTakeArgumentsFromFile.setText(_translate("dialogNewTrace", "Take from file"))
        self.buttonGetArgumentsFile.setText(_translate("dialogNewTrace", "..."))
        self.label_4.setText(_translate("dialogNewTrace", "Start directory"))
        self.buttonGetStartDirectory.setText(_translate("dialogNewTrace", "..."))
        self.buttonRunTrace.setText(_translate("dialogNewTrace", "Run"))
        self.buttonSaveTraceSettings.setText(_translate("dialogNewTrace", "Save"))
        self.buttonNewTraceCancel.setText(_translate("dialogNewTrace", "Cancel"))

